'use strict';

export const REFRESHING = 'REFRESHING';

export const SET_TOKEN = 'SET_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';
export const REGISTER_USER = 'REGISTER_USER';

export const LOAD_REQUEST_USER = 'LOAD_REQUEST_USER';

export const CLEAR_API_ERROR = 'CLEAR_API_ERROR';
export const API_ERROR = 'API_ERROR';


export const CREATE_WORKOUT = 'CREATE_WORKOUT';
export const GET_WORKOUTS = 'GET_WORKOUTS';


// Home Constants
export const LOAD_CLIENTS = 'LOAD_CLIENTS';
export const LOAD_WORKOUTS = 'LOAD_WORKOUTS';
export const DELETE_CLIENT = 'DELETE_CLIENT';
export const SEND_REQUEST = 'SEND_REQUEST';
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const READ_NOTIFICATION = 'READ_NOTIFICATION';

// Profile Constants
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_USER = 'UPDATE_USER';
export const GET_QUESTIONNAIRES = 'GET_QUESTIONNAIRES';
export const CREATE_QUESTIONNAIRE = 'CREATE_QUESTIONNAIRE';
