# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Trizing' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Trizing
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'Firebase/Messaging'

  target 'TrizingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Trizing-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Trizing-tvOS

  target 'Trizing-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
