# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'SimpleCoach' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleCoach
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'Firebase/Messaging', '4.0.0'
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

  target 'SimpleCoachTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SimpleCoach-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SimpleCoach-tvOS

  target 'SimpleCoach-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
