# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'TrainerBase' do
  pod 'Stripe', '~> 10.1.0'
  use_frameworks!

  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'Firebase/Messaging'
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  inherit! :search_paths

  target 'TrainerBaseTests' do
    inherit! :search_paths
  end

end
